paths:
  raw_videos: "data/raw/videos"
  raw_annotations: "/Users/ameliatuttle/Desktop/UJAnnChor-temp/Annotation Files/CSV Original Annotation Files"
  clips_index: "data/processed/clips.json"
  keypoints_dir: "data/processed/keypoints"
  splits_dir: "data/processed/splits"
  results_dir: "results"

dataset:
  fps: 25
  n_frames: 32
  n_joints: 17
  min_clip_duration: 0.3
  only_one_dancer_filter: false
  heatmap_size: 56
  heatmap_sigma: 3.0

split:
  train: 0.70
  val:   0.15
  test:  0.15
  seed: 42
  stratify_by: "label_fine"

pose:
  config: "/gpfsnyu/home/aat9362/.cache/torch/hub/checkpoints/rtmpose-m_8xb256-420e_body8-256x192.py"
  checkpoint: "/gpfsnyu/home/aat9362/.cache/torch/hub/checkpoints/rtmpose-m_simcc-body7_pt-body7_420e-256x192-e48f03d0_20230504.pth"
  device: "cuda:0"

train:
  batch_size: 32
  epochs: 100
  lr: 0.001
  weight_decay: 0.0001
  patience: 15
  num_workers: 4
  seed: 42

experiments:
  exp1:
    name: "MLP_xy_fine"
    model: "MLP"
    input: "xy"
    n_frames: 32
    label_type: "fine"

  exp2:
    name: "MLP_xyconf_fine"
    model: "MLP"
    input: "xyconf"
    n_frames: 32
    label_type: "fine"

  exp3:
    name: "TemporalCNN_xyconf_fine"
    model: "TemporalCNN"
    input: "xyconf"
    n_frames: 32
    label_type: "fine"

  exp4:
    name: "PoseConv3D_fine"
    model: "PoseConv3D"
    input: "heatmap"
    n_frames: 32
    label_type: "fine"

  exp5:
    name: "PoseConv3D_general"
    model: "PoseConv3D"
    input: "heatmap"
    n_frames: 32
    label_type: "general"

  exp4b:
    name: "PoseConv3D_fine_lowlr"
    model: "PoseConv3D"
    input: "heatmap"
    n_frames: 32
    label_type: "fine"
    lr: 0.0001
    batch_size: 8

  exp6:
    name: "PoseConv3D_large_fine"
    model: "PoseConv3DLarge"
    input: "heatmap"
    n_frames: 32
    label_type: "fine"
    lr: 0.0001
    batch_size: 8

  exp7:
    name: "PoseConv3D_joint_limb_fine"
    model: "PoseConv3D"
    input: "heatmap_joint_limb"
    n_frames: 32
    label_type: "fine"
    lr: 0.0001
    batch_size: 8

  exp8:
    name: "PoseSlowOnly_fine"
    model: "PoseSlowOnly"
    input: "heatmap_joint_limb"
    n_frames: 32
    label_type: "fine"
    lr: 0.0001
    batch_size: 8
